#! /bin/bash

ver="4.2.1"

download_suitesparse() {
    if [ -f ${packages_src_dir}/SuiteSparse-${ver}.tar.gz ]; then
        cp -R ${packages_src_dir}/SuiteSparse-${ver}.tar.gz ${src_dir}
    else
        wget -nv http://www.cise.ufl.edu/research/sparse/SuiteSparse/SuiteSparse-${ver}.tar.gz
    fi
}

unpack_suitesparse() {
    tar xzf SuiteSparse-${ver}.tar.gz
}

build_suitesparse() {
    cd ${src_dir}/SuiteSparse

    # We use CMake to look for BLAS and LAPACK
    # CMake will use the following SuiteSparse_config.mk.in as a template and
    # substitute @BLAS_FULL_LINKER_OPTIONS@ and @LAPACK_FULL_LINKER_OPTIONS@
    # with appropriate linking options, producing the file
    # SuiteSparse_config/SuiteSparse_config.mk
    mkdir cmake
    cd cmake

    if [ -z "${fortran_compiler}" ]; then
        fortran_compiler=gfortran
    fi
    cat > SuiteSparse_config.mk.in <<EOF
CF = \$(CFLAGS) \$(CPPFLAGS) \$(TARGET_ARCH) -O3 -fexceptions -fPIC
RANLIB = ranlib
ARCHIVE = \$(AR) \$(ARFLAGS)
CP = cp -f
MV = mv -f
F77 = ${fortran_compiler}
F77FLAGS = \$(FFLAGS) -O
F77LIB =
LIB = -lm
INSTALL_LIB = ${install_dir}/lib
INSTALL_INCLUDE = ${install_dir}/include
BLAS = @BLAS_FULL_LINKER_OPTIONS@
LAPACK = @LAPACK_FULL_LINKER_OPTIONS@
XERBLA = 
GPU_BLAS_PATH =
GPU_CONFIG =
METIS_PATH = ../../metis-4.0
METIS = ../../metis-4.0/libmetis.a
UMFPACK_CONFIG =
CHOLMOD_CONFIG = \$(GPU_CONFIG)
SPQR_CONFIG =
TBB =
CLEAN = *.o *.obj *.ln *.bb *.bbg *.da *.tcov *.gcov gmon.out *.bak *.d *.gcda *.gcno
EOF

    cat > CMakeLists.txt <<EOF
cmake_minimum_required(VERSION 2.8)
project(SuiteSparse)

set(CMAKE_PREFIX_PATH \${TPL_BLAS_DIR})
find_package(BLAS REQUIRED)
set(CMAKE_PREFIX_PATH \${TPL_LAPACK_DIR})
find_package(LAPACK REQUIRED)

set(FULL_LINK_OPTIONS "")
foreach(flag \${BLAS_LINKER_FLAGS})
    set(BLAS_FULL_LINKER_OPTIONS "\${BLAS_FULL_LINKER_OPTIONS} \${flag}")
endforeach(flag)
foreach(lib \${BLAS_LIBRARIES})
    set(BLAS_FULL_LINKER_OPTIONS "\${BLAS_FULL_LINKER_OPTIONS} -l\${lib}")
endforeach(lib)

set(LAPACK_FULL_LINK_OPTIONS "")
foreach(flag \${LAPACK_LINKER_FLAGS})
    set(LAPACK_FULL_LINKER_OPTIONS "\${LAPACK_FULL_LINKER_OPTIONS} \${flag}")
endforeach(flag)
foreach(lib \${LAPACK_LIBRARIES})
    set(LAPACK_FULL_LINKER_OPTIONS "\${LAPACK_FULL_LINKER_OPTIONS} -l\${lib}")
endforeach(lib)

configure_file(\${CMAKE_CURRENT_SOURCE_DIR}/SuiteSparse_config.mk.in \${CMAKE_CURRENT_SOURCE_DIR}/../SuiteSparse_config/SuiteSparse_config.mk @ONLY)
EOF

    cmake_bin=cmake
    if [ -n "${cmake_install_dir}" ]; then
        cmake_bin="${cmake_install_dir}/bin/cmake"
    fi
    ${cmake_bin} \
        -DTPL_BLAS_DIR:PATH=${blas_install_dir} \
        -DTPL_LAPACK_DIR:PATh=${lapack_install_dir} \
        .
    cd ..

    make library -j${num_proc}
}

install_suitesparse() {
    mkdir -p ${install_dir}/lib
    mkdir -p ${install_dir}/include

    make install
}


