#!/bin/bash
#
# Standard options for astyle
# Usage
# apply_astyle file(.cpp or .hpp)
# with apply_astyle --recursive "*.*pp"  you process all files recursively
#
astyle \
        --style=allman \
        \
        --indent=spaces=2  \
        --indent-switches \
        --indent-col1-comments \
        --indent-namespaces \
        \
        --pad-oper \
        --pad-paren-out \
        --pad-header \
        \
        --convert-tabs \
        --align-pointer=type \
        --max-instatement-indent=80 \
        --preserve-date \
        --lineend=linux \
        \
        --suffix=none \
        --verbose $*
	

#        --recursive "*.*pp"
