#!/bin/bash

if [ -z "$ROOT_DIR" ]; then
    ROOT_DIR=$PWD/../
fi

# select library installation path
if [ -z "${INSTALL_DIR}" ]; then
    INSTALL_DIR=${ROOT_DIR}/../install
fi

# select temporary build directory
if [ -z "$BUILD_DIR" ]; then
    BUILD_DIR="$INSTALL_DIR/build"
fi

if [ -z "$PACKAGE_SRC_DIR" ]; then
    PACKAGE_SRC_DIR="${ROOT_DIR}/external/src"
fi

# comment next line to keep build files
RM_TMP=1

# comment next line to avoid log files
LOG=1

# comment next line to disable download
DOWNLOAD=1

# comment next line to disable unpack
UNPACK=1

# set number of parallel builds to use
NUM_PROC=$(grep processor /proc/cpuinfo | wc -l)
if [ $NUM_PROC -gt 8 ]; then NUM_PROC=8; fi


