#!/bin/bash

# Detect if output is being redirected or piped
if [ -t 1 ]; then
    output_to_terminal=1
else
    output_to_terminal=""
fi

function echo_package_status ()
{
    package=$1
    i=$2
    max_i=$3
    status=$4
    if [ -n "${output_to_terminal}" ]; then
        ceol=`tput el` # clear to the end of line
        echo -n -e "\r${ceol}[$((i + 1))/${max_i}] ${package}: ${status}"
    else
        echo -n -e "${3}"
    fi
}

